### ISSUE TITLE
Fresh clone, following Readme.md instructions -> error in aws (Unexpected token export)

### ISSUE THREAD

**Issue by philipgloyne** [AnomalyInnovations/serverless-nodejs-starter#16]
Looks like it might be a Babel issue?

```
Syntax error in module 'handler': SyntaxError
(function (exports, require, module, __filename, __dirname) { export const hello = async (event, context, callback) => {
^^^^^^
SyntaxError: Unexpected token export
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```

**Comment by jayair** [comment]
@philipgloyne Hmm I'm not able to replicate it. Is this when you run the `serverless invoke local --function hello` command? Which version of serverless are you using?

**Comment by philipgloyne** [comment]
@jayair yes the local invoke command above works.
sls -version
1.16.0

**Comment by philipgloyne** [comment]
Upgrading serverless to 1.25.0 fixes the issue. Apologies, thanks for your help.
