### ISSUE TITLE
this.serverless.pluginManager.spawn is not a function

### ISSUE THREAD

**Issue by devanp92** [AnomalyInnovations/serverless-nodejs-starter#17]
I've tried to download and install the `hello` project but ran into the following issue when running `serverless deploy function --function hello`.

My Serverless version is `1.9.0`. I am assuming that this was a breaking change that was included in v.1.10.0 and that the solution is to upgrade `serverless?

```
  WARNING: You are running v1.9.0. v1.10.0 will include the following breaking changes:
    - Some lifecycle events for the deploy plugin will move to a new package plugin. More info -> https://git.io/vy1zC

  You can opt-out from these warnings by setting the "SLS_IGNORE_WARNING=*" environment variable.

Serverless: Deploying function: hello...
 
  Type Error ---------------------------------------------
 
     this.serverless.pluginManager.spawn is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: this.serverless.pluginManager.spawn is not a function
    at ServerlessWebpack.BbPromise.bind.then (/my-project/node_modules/serverless-webpack/index.js:96:51)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at PluginManager.run (~/.npm-packages/lib/node_modules/serverless/lib/classes/PluginManager.js:156:22)
    at Serverless.run (~/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:95:31)
    at serverless.init.then (~/.npm-packages/lib/node_modules/serverless/bin/serverless:23:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       9.4.0
     Serverless Version: 1.9.0
```

**Comment by devanp92** [comment]
Just realized that this was not the `serverless-webpack` repo 😅
