### ISSUE TITLE
Stacktrace doesn't show exact line number

### ISSUE THREAD

**Issue by Vadorequest** [AnomalyInnovations/serverless-nodejs-starter#20]
I have the following error and it doesn't show the exact line number unlike what it's supposed to.

I had an existing serverless app which I migrated towards this nodejs-starter a few minutes ago and trying it out.

```js
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at _callee$ (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/.webpack/service/feedback.js:111:25)
    at tryCatch (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at create (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/simulator-feedback/.webpack/service/feedback.js:143:17)
    at AwsInvokeLocal.invokeLocalNodeJs (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:338:12)
    at AwsInvokeLocal.invokeLocal (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:125:19)
    at AwsInvokeLocal.tryCatcher (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/vadorequest/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

package.json
```json
{
  "name": "aws-nodejs-typescript",
  "version": "1.0.0",
  "description": "Serverless webpack example using Typescript",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-plugin-source-map-support": "1.0.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-stage-3": "6.24.1",
    "serverless-webpack": "4.3.0",
    "webpack": "3.11.0",
    "webpack-node-externals": "1.6.0"
  },
  "author": "The serverless webpack authors (https://github.com/elastic-coders/serverless-webpack)",
  "license": "MIT",
  "dependencies": {
    "aws-sdk": "2.194.0",
    "babel-runtime": "6.26.0",
    "jest": "22.3.0",
    "moment": "2.20.1",
    "uuid": "3.2.1"
  }
}
```

webpack.config.js
```
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
};
```

.babelrc
```
{
  "plugins": ["transform-runtime"],
  "presets": ["env", "stage-3"]
}
```

AM I misunderstanding something or is there something wrong with my setup?

**Comment by jayair** [comment]
@Vadorequest Hmm your `.babelrc` and `webpack.config.js` are different form the ones in the repo. https://github.com/AnomalyInnovations/serverless-nodejs-starter/blob/master/webpack.config.js#L8 & https://github.com/AnomalyInnovations/serverless-nodejs-starter/blob/master/.babelrc#L2

**Comment by Vadorequest** [comment]
Indeed... How did I miss that -_-
Thanks!
