### ISSUE TITLE
Error in unit tests

### ISSUE THREAD

**Issue by thgh** [AnomalyInnovations/serverless-nodejs-starter#27]
After creating a project with this template, the tests don't run:

```sh
$ npm test

> chatbot@1.1.0 test /project
> jest

 FAIL  tests/handler.test.js
  ● Test suite failed to run

    /project/tests/handler.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as handler from '../handler';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at new Script (vm.js:51:7)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.531s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by jayair** [comment]
@thgh Hmm I can't replicate it. Which version of node are you using?

**Comment by thgh** [comment]
I think I messed up the `.babelrc` file. Works fine now 😀 

This project looks promising, will try it out next time!

**Comment by jeff-kilbride** [comment]
@thgh  I'm getting the same type of error:
```
$ yarn run test
yarn run v1.6.0
$ jest
 FAIL  tests/handler.test.js
  ✕ returns an alive status (1280ms)

  ● returns an alive status


    {"errorMessage":"Unexpected token import","errorType":"SyntaxError","stackTrace":["^^^^^^","","SyntaxError: Unexpected token import","createScript (vm.js:80:10)","Object.runInThisContext (vm.js:139:10)","Module._compile (module.js:616:28)","Object.Module._extensions..js (module.js:663:10)","Module.load (module.js:565:32)","tryModuleLoad (module.js:505:12)","Function.Module._load (module.js:497:3)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}


      at runSync (tests/lib/docker-lambda.js:71:13)
      at Object.<anonymous>.it (tests/handler.test.js:14:42)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.2s
Ran all test suites.
```
Can you explain what was messed up in your `.babelrc` file?

**Comment by jayair** [comment]
@jeff-kilbride Which version of Node are you running for your tests btw?

**Comment by jeff-kilbride** [comment]
@jayair  v8.10.0 -- however, I found the error. I was injecting the untranspiled code into a docker image. I had to move my docker volume mount to the `.webpack/service` directory to solve it.

**Comment by jayair** [comment]
@jeff-kilbride I see. Thanks for reporting back.
