### ISSUE TITLE
Cant load ".ejs" view. Please help me.

### ISSUE THREAD

**Issue by atodhruv** [AnomalyInnovations/serverless-nodejs-starter#30]
Error: Failed to lookup view "error" in views directory "/views"
    at EventEmitter.render (/var/task/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/var/task/node_modules/express/lib/response.js:971:7)
    at /var/task/webpack:/app.js:70:7
    at Layer.handle_error (/var/task/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/task/node_modules/express/lib/router/index.js:315:13)
    at /var/task/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12)
    at next (/var/task/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/task/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/task/node_modules/express/lib/router/index.js:315:13)
    at /var/task/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/var/task/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/var/task/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:674:20)
    at tryOnImmediate (timers.js:645:5)

**Comment by jayair** [comment]
@atodhruv It seems like it could find the file in the directory?

**Comment by atodhruv** [comment]
But there is file named "error.ejs" exist in /views folder

**Comment by atodhruv** [comment]
I think `res.render('view_name)` not working

**Comment by atodhruv** [comment]
It project structure is
-Project
   - controllers
   - views
   - services
   - node_modules
   - public
   - routes
   - app.js
   - lambda.js
   - serverless.yml
