### ISSUE TITLE
AWS_PROFILE=default serverless invoke local --function create --path mocks/create-event.json 

### ISSUE THREAD

**Issue by arpijoy** [AnomalyInnovations/serverless-nodejs-starter#46]
1. I completed building the create.js
2. Unable to run the create
AWS_PROFILE=default serverless invoke local --function create --path mocks/create-event.json 

I am blocked due to the following error:

 
Type Error ---------------------------------------------
 
  TypeError: Cannot create property 'events' on string 'create.main'
      at /usr/local/lib/node_modules/serverless/lib/classes/Service.js:146:45
      at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4905:15
      at baseForOwn (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:2990:24)
      at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4874:18
      at Function.forEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9342:14)
      at Service.setFunctionNames (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:144:7)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:110:20
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:699:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

**Comment by jayair** [comment]
Not sure what the issue is. Post your serverless.yml?
