### ISSUE TITLE
Can't create a project on Windows 10 - Request timed out

### ISSUE THREAD

**Issue by hejtful** [AnomalyInnovations/serverless-nodejs-starter#54]
I'm following the serverless-stack tutorial and got to [this chapter](https://serverless-stack.com/chapters/setup-the-serverless-framework.html), but I can't create a project using a Node.js starter.

```
serverless install --url https://github.com/AnomalyInnovations/serverless-nodejs-starter --name serverless-react-notes-app-api
Serverless: Downloading and installing "serverless-nodejs-starter"...
 
  Request Error ------------------------------------------
 
  RequestError: Request timed out
      at Timeout._onTimeout (C:\Users\budim\AppData\Roaming\npm\node_modules\serverless\node_modules\download\node_modules\got\index.js:433:24)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
```

Please let me know if I'm doing something wrong or if you need more info.

**Comment by hejtful** [comment]
Fixed by clearing npm cache and proxy settings, and rebooting my machine. Sorry for the unnecessary issue.
