### ISSUE TITLE
Cannot run sample project on aws lambda

### ISSUE THREAD

**Issue by firnandessicepat** [AnomalyInnovations/serverless-nodejs-starter#55]
Hi I am trying to use this awesome framework, but unfortunately the code won't run on aws lambda with this error:

```
{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is undefined or not exported",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is undefined or not exported",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1156:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)",
    "    at Module.load (internal/modules/cjs/loader.js:1000:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:899:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
    "    at internal/main/run_main_module.js:18:47"
  ]
}
```

I follow this step:
1. serverless install --url https://github.com/AnomalyInnovations/serverless-nodejs-starter --name my-project
2. cd my-project
3. npm install
4. serverless deploy (but it's error because i havn't setup my aws account to allow cloudformation stack)
5. So, i upload the file manually to my aws-lambda function. I upload zip from .serverless/hello.zip
6. Uploaded finished and i saved the code, run the test
7. Result is error

Please help me thanks

**Comment by jayair** [comment]
I haven't tried manually uploading it. And it seems like that doesn't work because the error is complaining about `index.handler` which we don't have defined in this starter.
